name: on-push

on: ["push"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: 🔁 ci

    runs-on:
      labels: ubuntu-latest

    env:
      NEXTAUTH_SECRET: ignore
      GOOGLE_CLIENT_ID: ignore,
      GOOGLE_CLIENT_SECRET: ignore
      GITHUB_OAUTH_TOKEN: ignore
      DATABASE_URL: http://example.com
      RESEND_API_KEY: ignore
      TEST_EMAIL_ADDRESS: noreply@example.com
      STRIPE_API_KEY: ignore
      STRIPE_WEBHOOK_SECRET: ignore
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID: ignore
      NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID: ignore
      NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID: ignore
      NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID: ignore
      EDGE_STORE_ACCESS_KEY: ignore
      EDGE_STORE_SECRET_KEY: ignore

    steps:
      - name: 🔸 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: 🦄 Format
        run: yarn format:check

      - name: 🎨 Lint
        run: yarn lint

      - name: 👷‍♂️ Build
        run: yarn build
